spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/macross?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 123456
  thymeleaf:
    mode: HTML
    prefix: classpath:/templates/
    encoding: UTF-8
    suffix: .html
  mvc:
    view:
      prefix: classpath:/templates/
      suffix: .html
  web:
    resources:
      chain:
        cache: true

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.macross.server.Entity
